"""
Django settings for mytech project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#armazene suas credenciais da API de vagas
ADZUNA_APP_ID = 'a9e8e5dc'
ADZUNA_APP_KEY = 'd98b82e07c18f3b16392397dfe0df9b1'
ADZUNA_API_BASE_URL = "http://api.adzuna.com/v1/api/jobs"
ADZUNA_COUNTRY_CODE = "br"  # ou outro código de país


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' :  timedelta(minutes = 5), #Duração do token de acesso é de 5 min
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=1), #Duração de token refresh
    'ROTATE_REFRESH_TOKENS': True, #Gera um token refresh, cada vez q o refresh gerar um token access
    'BLACKLIST_AFTER_ROTATION': True, #Coloca o ultimo refresh no blacklist
    'ALGORITHM': 'HS256',
    'SIGNING_KEY':'956b3a2efd8fa533937a0fce0e883de1c2ed0c5585908eaefb8cf97a703325bb' #Assinatura do jwt
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',  # Nome da tabela onde o cache será armazenado
    }
}



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d_sf_kc!dmwoo80er-3&pu)($d6+3a3y35rbhg08na2t4kh@^p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vagasEmpregoAPI',
    'noticiaTech',
    'login',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist'
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mytech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mytech.wsgi.application'

REST_FRAMEWORK = {
    # Configuração de autenticação
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
   'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # <- isso pode bloquear
    ],

    # Configuração de paginação
    'DEFAULT_PAGINATION_CLASS': 'vagasEmpregoAPI.paginations.CustomPagination',  # Ajuste o caminho conforme o nome do seu app
    'PAGE_SIZE': 10,
    
    #Configura o acesso de usuario na view
    'DEFAULT_THROTTLE_CLASSES': [
            'rest_framework.throttling.UserRateThrottle',
            'rest_framework.throttling.AnonRateThrottle',
        ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '20/minute',   # autenticado: 10 requisições por minuto
        'anon': '10/minute',    # anônimo: 3 requisições por minuto
        'ten' : '10/minute',   # Personalizada 
    }
}



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SECURE_SSL_REDIRECT = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


