# Generated by Django 5.1.7 on 2025-03-19 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=70)),
                ('Empresa', models.CharField(max_length=70)),
                ('Localizacao', models.CharField(max_length=200)),
                ('Descricao', models.TextField()),
                ('DataPublicacao', models.DateField(verbose_name=datetime.datetime(2025, 3, 19, 18, 46, 26, 766727))),
            ],
        ),
    ]
