# Generated by Django 5.1.7 on 2025-03-19 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='DataPublicacao',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 19, 18, 49, 30, 746364)),
        ),
    ]
