# Generated by Django 5.1 on 2025-03-21 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0002_alter_vagas_datapublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='DataPublicacao',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 21, 10, 23, 32, 456649)),
        ),
    ]
