# Generated by Django 5.1 on 2025-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0003_alter_vagas_datapublicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='url',
            field=models.URLField(default='None'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='DataPublicacao',
            field=models.DateField(),
        ),
    ]
