# Generated by Django 5.1.7 on 2025-03-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0004_vagas_url_alter_vagas_datapublicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagas',
            old_name='Título',
            new_name='Titulo',
        ),
    ]
