# Generated by Django 5.1.7 on 2025-03-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0005_rename_título_vagas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='DataPublicacao',
        ),
    ]
