# Generated by Django 5.1.7 on 2025-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0006_remove_vagas_datapublicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='bol',
            field=models.BooleanField(default=False),
        ),
    ]
