# Generated by Django 5.1.7 on 2025-04-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0007_vagas_bol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='bol',
        ),
    ]
