# Generated by Django 5.1.7 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0008_remove_vagas_bol'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='id_externa',
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
    ]
