# Generated by Django 5.1.7 on 2025-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0010_alter_vagas_id_externa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='id_externa',
            field=models.CharField(default='NULO', max_length=100, null=True, unique=True),
        ),
    ]
