# Generated by Django 5.1.7 on 2025-04-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagasEmpregoAPI', '0011_alter_vagas_id_externa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='id_externa',
        ),
    ]
