# Generated by Django 5.1.7 on 2025-04-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('fonte', models.URLField(default='Nulo')),
            ],
        ),
    ]
