# Generated by Django 5.1.7 on 2025-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiaTech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fonte',
            field=models.URLField(default='Nulo', null=True),
        ),
    ]
