# Generated by Django 5.1.7 on 2025-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiaTech', '0002_alter_noticia_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
