# Generated by Django 5.1.7 on 2025-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('Nome', models.CharField(max_length=100)),
                ('Senha', models.CharField(max_length=50)),
                ('Cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
    ]
