# Generated by Django 5.1.7 on 2025-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
